name: book_instagram_for_firebase
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  community_material_icon: ^5.9.55
  settings_ui: ^2.0.2
  url_launcher: ^6.0.18
  in_app_review: ^2.0.4
  pull_to_refresh: ^2.0.0
  dotted_border: 2.0.0
  heroicons: 0.4.0
  flutter_launcher_icons: ^0.9.2
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  firebase_core: ^1.12.0
  firebase_auth: 2.0.0
  cloud_firestore: 1.0.7
  firebase_storage: 9.0.0
  #image picker
  image_picker: ^0.8.4+10
  #share contents
  share: ^2.0.4
  #adapting screen and font size
  flutter_screenutil: ^5.4.0
  flutter_native_splash: ^2.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/nolist.png
    - assets/images/check_email.png
flutter_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  fullscreen: true