name: book_instagram_for_firebase
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  community_material_icon: ^5.9.55
  settings_ui: ^2.0.2
  url_launcher: ^6.0.18
  in_app_review: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  firebase_core: ^1.12.0
  firebase_auth: 2.0.0
  cloud_firestore: 1.0.7
  firebase_storage: 9.0.0
  #image picker
  image_picker: ^0.8.4+10
  #share contents
  share: ^2.0.4
  #adapting screen and font size
  flutter_screenutil: ^5.4.0
  dotted_border: ^2.0.0+2
flutter:
  uses-material-design: true
